#!/usr/bin/env bash

set -Eeuo pipefail

REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)"

# shellcheck disable=SC1091
source "${REPO_ROOT}/aim.sh"

[[ "$(buffer_pool_megabytes 2048)" == 128 ]]
[[ "$(buffer_pool_megabytes 3072)" == 128 ]]
[[ "$(buffer_pool_megabytes 4096)" == 1024 ]]
[[ "$(buffer_pool_megabytes 16384)" == 8192 ]]

tmp="$(mktemp -d /tmp/aim-resume-test.XXXXXX)"
cleanup() { rm -rf -- "$tmp"; }
trap cleanup EXIT

VERSION="8.0.46"
SERIES="8.0"
PORT=3319
ROLE="mgr"
BIND_ADDRESS="0.0.0.0"
SERVER_ID=101
MGR_LOCAL_ADDRESS="10.17.0.12"
MGR_PORT=33061
MGR_SEEDS="10.17.0.12:33061,10.17.0.13:33061,10.17.0.89:33061"
MGR_GROUP_NAME="aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"
MGR_ALLOWLIST="10.17.0.12,10.17.0.13,10.17.0.89"
BASE_ROOT="$tmp/opt/mysql"
DATA_ROOT="$tmp/data/mysql"
LOG_ROOT="$tmp/log/mysql"
TMP_ROOT="$tmp/tmp/mysql"
DRY_RUN=1
derive_instance_paths

(
    DRY_RUN=0
    config_owner=""
    memory_megabytes() { printf '2048\n'; }
    chown() {
        if [[ "$1" == -R ]]; then
            config_owner="$MYSQL_USER"
            return
        fi
        [[ "$1" == "root:$MYSQL_GROUP" && "$2" == "$CNF_FILE" ]]
        config_owner=root
    }
    write_config
    [[ "$config_owner" == root ]] || {
        printf 'write_config left my.cnf owned by %s instead of root\n' "$config_owner" >&2
        exit 1
    }
)

mkdir -p "$BASEDIR/bin" "$(dirname -- "$CNF_FILE")"
cat >"$BASEDIR/bin/mysqld" <<'EOF'
#!/usr/bin/env bash
printf 'mysqld  Ver 8.0.46 for Linux on x86_64 (MySQL Community Server - GPL)\n'
EOF
chmod 0755 "$BASEDIR/bin/mysqld"
cp "$BASEDIR/bin/mysqld" "$MYSQL"
cp "$BASEDIR/bin/mysqld" "$MYSQLADMIN"
cat >"$CNF_FILE" <<EOF
# Generated by AIM 2.3.1; instance 3319, MySQL 8.0.46.
[mysqld]
port = 3319
bind_address = 0.0.0.0
server_id = 101
basedir = $BASEDIR
datadir = $DATADIR
socket = $SOCKET
innodb_buffer_pool_size = 128M
plugin_load_add = group_replication.so
report_host = 10.17.0.12
loose-group_replication_group_name = aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee
loose-group_replication_local_address = 10.17.0.12:33061
loose-group_replication_group_seeds = 10.17.0.12:33061,10.17.0.13:33061,10.17.0.89:33061
loose-group_replication_ip_allowlist = 10.17.0.12,10.17.0.13,10.17.0.89
EOF

(
    DRY_RUN=0
    config_owner=1001
    stat() { printf '%s\n' "$config_owner"; }
    id() {
        [[ "$1" == -u && "$2" == "$MYSQL_USER" ]]
        printf '1001\n'
    }
    find() { return 0; }
    chown() {
        [[ "$1" == "root:$MYSQL_GROUP" && "$2" == "$CNF_FILE" ]]
        config_owner=0
    }
    chmod() { [[ "$1" == 640 && "$2" == "$CNF_FILE" ]]; }
    secure_mysql_binary_tree() { :; }
    validate_resumable_instance
    [[ "$config_owner" == 0 ]] || {
        printf 'resume did not repair legacy mysql-owned my.cnf\n' >&2
        exit 1
    }
)

if (
    DRY_RUN=0
    stat() { printf '2002\n'; }
    id() { printf '1001\n'; }
    find() { return 0; }
    validate_resumable_instance
) >/dev/null 2>&1; then
    printf 'resume accepted a configuration owned by an unrelated user\n' >&2
    exit 1
fi

validate_resumable_instance
sed -i.bak 's/server_id = 101/server_id = 999/' "$CNF_FILE"
if (validate_resumable_instance) >/dev/null 2>&1; then
    printf 'resume accepted a mismatched server_id\n' >&2
    exit 1
fi

printf 'low-memory sizing, config ownership, and bounded resume validation: ok\n'
