#!/usr/bin/env bash

set -Eeuo pipefail

REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)"

# shellcheck disable=SC1091
source "${REPO_ROOT}/aim.sh"

[[ "$(buffer_pool_megabytes 2048)" == 128 ]]
[[ "$(buffer_pool_megabytes 3072)" == 128 ]]
[[ "$(buffer_pool_megabytes 4096)" == 1024 ]]
[[ "$(buffer_pool_megabytes 16384)" == 8192 ]]

tmp="$(mktemp -d /tmp/aim-resume-test.XXXXXX)"
cleanup() { rm -rf -- "$tmp"; }
trap cleanup EXIT

VERSION="8.0.46"
SERIES="8.0"
PORT=3319
ROLE="mgr"
BIND_ADDRESS="0.0.0.0"
SERVER_ID=101
MGR_LOCAL_ADDRESS="10.17.0.12"
MGR_PORT=33061
MGR_SEEDS="10.17.0.12:33061,10.17.0.13:33061,10.17.0.89:33061"
MGR_GROUP_NAME="aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"
MGR_ALLOWLIST="10.17.0.12,10.17.0.13,10.17.0.89"
BASE_ROOT="$tmp/opt/mysql"
DATA_ROOT="$tmp/data/mysql"
LOG_ROOT="$tmp/log/mysql"
TMP_ROOT="$tmp/tmp/mysql"
DRY_RUN=1
derive_instance_paths
mkdir -p "$BASEDIR/bin" "$(dirname -- "$CNF_FILE")"
cat >"$BASEDIR/bin/mysqld" <<'EOF'
#!/usr/bin/env bash
printf 'mysqld  Ver 8.0.46 for Linux on x86_64 (MySQL Community Server - GPL)\n'
EOF
chmod 0755 "$BASEDIR/bin/mysqld"
cp "$BASEDIR/bin/mysqld" "$MYSQL"
cp "$BASEDIR/bin/mysqld" "$MYSQLADMIN"
cat >"$CNF_FILE" <<EOF
# Generated by AIM 2.3.1; instance 3319, MySQL 8.0.46.
[mysqld]
port = 3319
bind_address = 0.0.0.0
server_id = 101
basedir = $BASEDIR
datadir = $DATADIR
socket = $SOCKET
innodb_buffer_pool_size = 128M
plugin_load_add = group_replication.so
report_host = 10.17.0.12
loose-group_replication_group_name = aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee
loose-group_replication_local_address = 10.17.0.12:33061
loose-group_replication_group_seeds = 10.17.0.12:33061,10.17.0.13:33061,10.17.0.89:33061
loose-group_replication_ip_allowlist = 10.17.0.12,10.17.0.13,10.17.0.89
EOF

validate_resumable_instance
sed -i.bak 's/server_id = 101/server_id = 999/' "$CNF_FILE"
if (validate_resumable_instance) >/dev/null 2>&1; then
    printf 'resume accepted a mismatched server_id\n' >&2
    exit 1
fi

printf 'low-memory sizing and bounded resume validation: ok\n'
