package console

import (
	"bytes"
	"errors"
	"fmt"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"

	"github.com/google/uuid"
)

type DeploymentScriptExport struct {
	Filename       string   `json:"filename"`
	Content        string   `json:"content"`
	Instructions   []string `json:"instructions"`
	SecretsOmitted bool     `json:"secrets_omitted"`
}

var scriptFilenamePattern = regexp.MustCompile(`[^A-Za-z0-9._-]+`)

// BuildDeploymentScript converts the same validated deployment specification
// used by the web console into a secrets-free wrapper around the Host Kit
// scripts. Passwords are deliberately requested on the target host so they do
// not enter the browser preview, clipboard history, shell history or argv.
func BuildDeploymentScript(input DeploymentRequest, media *Media) (DeploymentScriptExport, error) {
	if strings.ContainsAny(input.Name, "\r\n\x00") {
		return DeploymentScriptExport{}, errors.New("部署名称不能包含控制字符")
	}
	validation := input
	if validation.Mode == "replica" && validation.SourcePassword == "" {
		validation.SourcePassword = "prompt-on-target"
	}
	if err := validateDeployment(&validation); err != nil {
		return DeploymentScriptExport{}, err
	}
	input = validation
	if input.Mode == "mgr" && input.MGRGroupName == "" {
		input.MGRGroupName = uuid.NewString()
	}
	if media != nil {
		if media.ID != input.MediaID || media.Version != input.Version || filepath.Base(media.Filename) != media.Filename || len(media.SHA256) != 64 {
			return DeploymentScriptExport{}, errors.New("所选安装介质与部署规格不一致")
		}
	}
	input.RootPassword, input.ReplicationPassword, input.SourcePassword, input.MGRRecoveryPassword, input.MGRAdminPassword = "", "", "", "", ""

	var script bytes.Buffer
	line := func(format string, args ...any) { fmt.Fprintf(&script, format+"\n", args...) }
	line("#!/usr/bin/env bash")
	line("# Generated by aim.sh MySQL Console. Review before running.")
	line("# Deployment: %s", input.Name)
	line("# This file intentionally contains no database passwords.")
	line("")
	line("set -Eeuo pipefail")
	line("umask 077")
	line("")
	line("readonly DEPLOYMENT_NAME=%s", shellQuote(input.Name))
	line("readonly MODE=%s", shellQuote(input.Mode))
	line("readonly MYSQL_VERSION=%s", shellQuote(input.Version))
	line("readonly MYSQL_PORT=%s", shellQuote(strconv.Itoa(input.Port)))
	line("readonly BIND_ADDRESS=%s", shellQuote(input.BindAddress))
	line("readonly NODE_COUNT=%d", len(input.Nodes))
	line("readonly AIM_SH=\"${AIM_SH:-/opt/aim/aim.sh}\"")
	line("readonly ROUTER_SH=\"${ROUTER_SH:-/opt/aim/router.sh}\"")
	line("")
	line("NODE_IPS=(%s)", shellArray(nodeStrings(input.Nodes, func(node DeploymentNode) string { return node.LocalIP })))
	line("NODE_SERVER_IDS=(%s)", shellArray(nodeStrings(input.Nodes, func(node DeploymentNode) string { return strconv.FormatUint(uint64(node.ServerID), 10) })))
	line("NODE_ROUTER_IPS=(%s)", shellArray(nodeStrings(input.Nodes, func(node DeploymentNode) string { return node.RouterIP })))
	line("")
	line("die() { printf 'aim-export: ERROR: %%s\\n' \"$*\" >&2; exit 1; }")
	line("note() { printf 'aim-export: %%s\\n' \"$*\"; }")
	line("require_secret() {")
	line("  local variable=\"$1\" label=\"$2\" value")
	line("  [[ -n \"${!variable:-}\" ]] && return")
	line("  [[ -t 0 ]] || die \"$variable is required in non-interactive mode\"")
	line("  IFS= read -r -s -p \"$label: \" value; printf '\\n'")
	line("  [[ -n \"$value\" ]] || die \"$label cannot be empty\"")
	line("  printf -v \"$variable\" '%%s' \"$value\"")
	line("  export \"$variable\"")
	line("}")
	line("")
	line("select_node() {")
	line("  local requested=\"${AIM_NODE_INDEX:-}\" matches=0 candidate=0 addresses index expected")
	line("  if (( NODE_COUNT == 1 )); then NODE_INDEX=1; return; fi")
	line("  if [[ -n \"$requested\" ]]; then")
	line("    [[ \"$requested\" =~ ^[1-9][0-9]*$ ]] || die 'AIM_NODE_INDEX must be a positive integer'")
	line("    (( requested <= NODE_COUNT )) || die 'AIM_NODE_INDEX exceeds the node count'")
	line("    NODE_INDEX=$requested; return")
	line("  fi")
	line("  command -v ip >/dev/null 2>&1 || die 'ip command is required for automatic node detection; alternatively set AIM_NODE_INDEX'")
	line("  addresses=\" $(ip -o -4 addr show | awk '{split($4,a,\"/\"); printf \"%%s \",a[1]}') \"")
	line("  for (( index=0; index<NODE_COUNT; index++ )); do")
	line("    expected=\"${NODE_IPS[$index]}\"")
	line("    if [[ -n \"$expected\" && \"$addresses\" == *\" $expected \"* ]]; then matches=$((matches+1)); candidate=$((index+1)); fi")
	line("  done")
	line("  (( matches == 1 )) || die 'cannot uniquely match this host to a configured business IP; set AIM_NODE_INDEX=1..N'")
	line("  NODE_INDEX=$candidate")
	line("}")
	line("")
	line("verify_archive() {")
	if media == nil {
		line("  return")
	} else {
		line("  local expected=%s actual", shellQuote(strings.ToLower(media.SHA256)))
		line("  ARCHIVE_PATH=\"${AIM_ARCHIVE_PATH:-./%s}\"", media.Filename)
		line("  [[ -f \"$ARCHIVE_PATH\" ]] || die \"installation archive not found: $ARCHIVE_PATH\"")
		line("  if command -v sha256sum >/dev/null 2>&1; then actual=\"$(sha256sum \"$ARCHIVE_PATH\" | awk '{print $1}')\"")
		line("  elif command -v shasum >/dev/null 2>&1; then actual=\"$(shasum -a 256 \"$ARCHIVE_PATH\" | awk '{print $1}')\"")
		line("  else die 'sha256sum or shasum is required to verify the installation archive'; fi")
		line("  [[ \"${actual,,}\" == \"$expected\" ]] || die 'installation archive SHA-256 mismatch'")
	}
	line("}")
	line("")
	line("prompt_install_secrets() {")
	line("  require_secret AIM_ROOT_PASSWORD 'MySQL root password'")
	switch input.Mode {
	case "source", "replication":
		line("  require_secret AIM_REPL_PASSWORD 'replication password'")
	case "replica":
		line("  require_secret AIM_SOURCE_PASSWORD 'source replication password'")
	case "mgr":
		line("  require_secret AIM_MGR_RECOVERY_PASSWORD 'shared MGR recovery password'")
		if input.DeployRouter {
			line("  require_secret AIM_MGR_ADMIN_PASSWORD 'InnoDB Cluster administrator password'")
		}
	}
	line("}")
	line("")
	line("install_mysql() {")
	line("  [[ $EUID -eq 0 ]] || die 'run this script as root, for example: sudo bash ./$(basename \"$0\") install'")
	line("  [[ -x \"$AIM_SH\" ]] || die \"Host Kit aim.sh is missing or not executable: $AIM_SH\"")
	line("  local slot=$((NODE_INDEX-1)) role=\"$MODE\" local_ip=\"${NODE_IPS[$slot]}\" server_id=\"${NODE_SERVER_IDS[$slot]}\"")
	if input.Mode == "replication" {
		line("  if (( NODE_INDEX == 1 )); then role=source; else role=replica; AIM_SOURCE_PASSWORD=\"$AIM_REPL_PASSWORD\"; export AIM_SOURCE_PASSWORD; fi")
	}
	line("  local args=(-v \"$MYSQL_VERSION\" -p \"$MYSQL_PORT\" --base-root /opt/mysql --data-root /data/mysql --log-root /var/log/mysql --tmp-root /var/tmp/mysql --machine-readable --no-print-secrets --role \"$role\" --bind-address \"$BIND_ADDRESS\")")
	line("  [[ \"$server_id\" == 0 ]] || args+=(--server-id \"$server_id\")")
	switch input.Mode {
	case "source":
		line("  args+=(--replica-host %s --repl-user %s)", shellQuote(input.ReplicaHost), shellQuote(input.ReplicationUser))
	case "replica":
		line("  args+=(--source-host %s --source-port %d --source-user %s)", shellQuote(input.SourceHost), input.SourcePort, shellQuote(input.ReplicationUser))
	case "replication":
		line("  if (( NODE_INDEX == 1 )); then args+=(--replica-host %s --repl-user %s)", shellQuote(input.Nodes[1].LocalIP), shellQuote(input.ReplicationUser))
		line("  else args+=(--source-host %s --source-port %d --source-user %s); fi", shellQuote(input.Nodes[0].LocalIP), input.SourcePort, shellQuote(input.ReplicationUser))
	case "mgr":
		seeds := make([]string, 0, len(input.Nodes))
		adminHosts := make([]string, 0, len(input.Nodes))
		for _, node := range input.Nodes {
			seeds = append(seeds, fmt.Sprintf("%s:%d", node.LocalIP, input.MGRPort))
			adminHosts = append(adminHosts, node.LocalIP)
		}
		line("  args+=(--mgr-local-address \"$local_ip\" --mgr-port %d --mgr-seeds %s --mgr-group-name %s --mgr-allowlist %s --mgr-recovery-user %s)", input.MGRPort, shellQuote(strings.Join(seeds, ",")), shellQuote(input.MGRGroupName), shellQuote(input.MGRAllowlist), shellQuote(input.MGRRecoveryUser))
		line("  (( NODE_INDEX == 1 )) && args+=(--mgr-bootstrap)")
		if input.DeployRouter {
			line("  args+=(--mgr-admin-user %s --mgr-admin-hosts %s)", shellQuote(input.MGRAdminUser), shellQuote(strings.Join(adminHosts, ",")))
		}
	}
	if media != nil {
		line("  verify_archive")
		line("  args+=(--archive \"$ARCHIVE_PATH\" --no-download)")
	}
	line("  note \"installing node $NODE_INDEX/$NODE_COUNT as $role\"")
	line("  \"$AIM_SH\" \"${args[@]}\"")
	line("}")
	line("")
	line("install_router() {")
	if input.DeployRouter {
		adminHosts := make([]string, 0, len(input.Nodes))
		for _, node := range input.Nodes {
			adminHosts = append(adminHosts, node.LocalIP)
		}
		line("  [[ $EUID -eq 0 ]] || die 'run this script as root'")
		line("  [[ -x \"$ROUTER_SH\" ]] || die \"Host Kit router.sh is missing or not executable: $ROUTER_SH\"")
		line("  require_secret AIM_MGR_ADMIN_PASSWORD 'InnoDB Cluster administrator password'")
		line("  local slot=$((NODE_INDEX-1)) bind_ip=\"${NODE_ROUTER_IPS[$slot]}\"")
		line("  local args=(--mysql-version \"$MYSQL_VERSION\" --mysql-port \"$MYSQL_PORT\" --cluster-name %s --bind-address \"$bind_ip\" --rw-port %d --admin-user %s --admin-hosts %s --base-root /opt/mysql --data-root /data/mysql)", shellQuote(input.RouterClusterName), input.RouterRWPort, shellQuote(input.MGRAdminUser), shellQuote(strings.Join(adminHosts, ",")))
		line("  (( NODE_INDEX == 1 )) && args+=(--adopt)")
		line("  note \"deploying MySQL Router on node $NODE_INDEX/$NODE_COUNT at $bind_ip:%d\"", input.RouterRWPort)
		line("  \"$ROUTER_SH\" \"${args[@]}\"")
	} else {
		line("  die 'Router was not enabled in this deployment specification'")
	}
	line("}")
	line("")
	line("usage() {")
	actions := ""
	if input.DeployRouter {
		actions = "|router"
	}
	line("  printf 'Usage: sudo bash %%s install%s\\n' \"$(basename \"$0\")\"", actions)
	line("  printf 'Set AIM_NODE_INDEX=1..%%s if automatic IP detection is unavailable.\\n' \"$NODE_COUNT\"")
	line("}")
	line("")
	line("case \"${1:-install}\" in -h|--help|help) usage; exit 0 ;; esac")
	line("select_node")
	line("case \"${1:-install}\" in")
	line("  install) [[ $EUID -eq 0 ]] || die 'run this script as root'; prompt_install_secrets; install_mysql ;;")
	if input.DeployRouter {
		line("  router) [[ $EUID -eq 0 ]] || die 'run this script as root'; install_router ;;")
	}
	line("  *) usage >&2; exit 2 ;;")
	line("esac")

	filename := strings.Trim(scriptFilenamePattern.ReplaceAllString(input.Name, "-"), "-._")
	if filename == "" {
		filename = "mysql-deployment"
	}
	instructions := []string{
		"目标机需先通过 Host Kit 2.4.5 安装 /opt/aim/aim.sh；脚本本身不包含数据库密码。",
		"复制脚本到目标机，chmod 700 后以 root 执行；密码会在目标机终端静默询问。",
	}
	if len(input.Nodes) > 1 {
		instructions = append(instructions, "将同一脚本复制到所有节点并按页面顺序执行 install；脚本会按业务网 IP 自动识别节点，必要时可设置 AIM_NODE_INDEX=1..N。")
	}
	if input.DeployRouter {
		instructions = append(instructions, "先在 1、2、3 节点依次执行 install；三节点 MGR 全部 ONLINE 后，再在 1、2、3 节点依次执行 router。")
	}
	if media != nil {
		instructions = append(instructions, fmt.Sprintf("把 %s 一并复制到目标机当前目录，或通过 AIM_ARCHIVE_PATH 指定路径；脚本会校验 SHA-256。", media.Filename))
	}
	return DeploymentScriptExport{Filename: "aim-" + filename + ".sh", Content: script.String(), Instructions: instructions, SecretsOmitted: true}, nil
}

func nodeStrings(nodes []DeploymentNode, value func(DeploymentNode) string) []string {
	result := make([]string, 0, len(nodes))
	for _, node := range nodes {
		result = append(result, value(node))
	}
	return result
}

func shellArray(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, shellQuote(value))
	}
	return strings.Join(quoted, " ")
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\\''") + "'"
}
